#+TITLE: sta-latex: A Guide To.
#                               ____  _      _         _         _____   __  __
#                              / ___|| |_   / \       | |    __ |_   _|__\ \/ /
#                              \___ \| __| / _ \ _____| |   / _` || |/ _ \\  / 
#                               ___) | |_ / ___ \_____| |__| (_| || |  __//  \ 
#                              |____/ \__/_/   \_\    |_____\__,_||_|\___/_/\_\
#

* Overview

A LaTeX project for use within the University of St Andrews, and
especially within the School of Computer Science. The files here are
provided under the LaTeX Project Public License v1.3c. Currently the
following files are available:

+ sta-thesis.cls :: An overlay of the memoir class, with helper code
                    and preloaded packages, designed for writing
                    doctoral theses.
+ sta-colours.sty :: The university colours.
+ sta-letter.cls :: An overlay of the memoir class, with helper code
                    and some preloaded packages, designed for writing
                    formal letters.
+ sta-poster.sty :: A style, and convenience, file for the baposter
                    class. baposter, is a LaTeX class for producing
                    posters.
+ sta-drafting.sty :: A drafting configuration.
+ stabs.sty :: A beamer styling package that provides default themes
               and other goodness for producing both lectures and
               conference presentations.
+ stabsmemoir.sty :: Beamer article notes stylingk for memoir.

The classes have been designed to adhere closely as possible to the
University of St Andrews' corporate guidelines, and be used with a
vanila LaTeX install. =Baposter= is the exception to the rule. If you
know of *better* preinstalled LaTeX poster classes please let me know.

+ Note :: This project is under perpetual development, and so mistakes
          will be made. Any problems please submit an issue with
          a *MINIMAL FAILING EXAMPLE* to the issue tracker.

+ Note ::  This project is not officially affiliated with the
           University nor the department.

Pull requests will be welcomed, though I do not guarantee that they
will be accepted. Any ideas for features/improvements to the existing
packages, or ideas for new classes/packages please use githubs issue
tracker.

The *examples* folder contains some example classes, and shows how I
intend the packages to be used.

* Installation

1. Add a folder =sta-latex= under =texmf/tex/latex/= within your
local =texmf= tree.
 + *Linux* :  it is =~=
 + *Mac OS X* : it is in =~/Library=
 + *Windows* : no idea/do not care
2. Copy the files into the directory.
3. Run =texhash= n.b. you may have to do this under root. 
